version: "3.8"

services:
  link:
    image: ppzxc8487/go-link:v0.0.24
    restart: always
    container_name: link
    volumes:
      - ./config.json:/app/config.json
      - ./static:/app/static
      - ./uploads:/app/uploads
    ports:
      - 8283:8283
    networks:
      - link
      
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    #volumes:
    #  - ./mongodb/data:/data/db
    networks:
      - link

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8284:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    networks:
      - link
      
#  mariadb:
#    image: mariadb:10.3
#    restart: always
#    container_name: mariadb
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_DATABASE=test
#      - MYSQL_USER=test
#      - MYSQL_PASSWORD=test
#      - MYSQL_ROOT_PASSWORD=test
#      - TZ=Asia/Seoul
#    volumes:
#      - ./mariadb/my.cnf:/root/.my.cnf:ro
#      - ./mariadb/conf.d:/etc/mysql/conf.d:ro
#      - ./mariadb/1.sql:/docker-entrypoint-initdb.d/1.sql:ro
#    networks:
#      - link
      
networks:
  link:
    external: true
